routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'AuthController@login')->name('login');
Route::post('authenticating', 'AuthController@authenticating')->name('authenticating');

Route::group(['middleware' => ['auth']], function() {
    Route::post('logout', 'AuthController@logout')->name('logout');
    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::resource('user', 'UserController');
    Route::resource('jabatan', 'JabatanController');
    Route::resource('kategori', 'KategoriController');
    Route::resource('dokumen', 'DokumenController');
    Route::get('dokumen/verify/{id}', 'DokumenController@verify')->name('dokumen.verify');
    Route::get('diskusi', 'DiskusiController@index')->name('diskusi.index');
    Route::post('diskusi/getMessage', 'DiskusiController@getMessage')->name('diskusi.getMessage');
    Route::post('diskusi/sentMessage', 'DiskusiController@sentMessage')->name('diskusi.sentMessage');
    Route::post('diskusi/createChannel', 'DiskusiController@createChannel')->name('diskusi.createChannel');
    Route::post('diskusi/addpartisipant', 'DiskusiController@addUser')->name('diskusi.addPartisipant');
    Route::post('diskusi/createTag', 'DiskusiController@createTag')->name('diskusi.createtag');
});

app/Models/Jabatan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Jabatan extends Model
{
    protected $table = 'jabatan';

    protected $fillable = [
        'jabatan_name',
        'access_knowledge_document',
        'upload_knowledge_document',
        'download_knowledge_document',
        'verification_knowledge_document',
        'create_channel_discussion',
        'verification_channel_discussion',
        'manage_knowledge_document',
        'manage_channel_discussion'
    ];
}

app/Http/Controllers/JabatanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Jabatan;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\DataTables;

class JabatanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Jabatan::all();
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $btn = '
                    <form action="' . route('jabatan.destroy', $row->id) . '" method="POST" id="delete-form">
                    ' . csrf_field() . '
                    ' . method_field('DELETE') . '
                        <a href="' . route('jabatan.edit', $row->id) . '" data-toggle="tooltip" title="Edit Jabatan" class="btn btn-warning btn-circle btn-sm edit"><i class="fas fa-edit"></i></a>
                        <button type="submit" id="btn-submit" class="btn btn-danger btn-circle btn-sm" data-toggle="tooltip" title="Hapus Jabatan">
                            <i class="fas fa-trash"></i>
                        </button>
                    </form>
                    ';
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('jabatan.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('jabatan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = Validator::make($request->all(), [
            'jabatan_name' => 'required|unique:jabatan,jabatan_name'
        ]);

        if ($validate->fails()) {
            return redirect()->back()->with('error', $validate->errors()->first())->withInput();
        }

        try {
            $jabatan = Jabatan::create([
                'jabatan_name' => $request->jabatan_name,
                'access_knowledge_document' => $request->access_knowledge_document ? true : false,
                'upload_knowledge_document' => $request->upload_knowledge_document ? true : false,
                'download_knowledge_document' => $request->download_knowledge_document ? true : false,
                'verification_knowledge_document' => $request->verification_knowledge_document ? true : false,
                'create_channel_discussion' => $request->create_channel_discussion ? true : false,
                'verification_channel_discussion' => $request->verification_channel_discussion ? true : false,
                'manage_knowledge_document' => $request->manage_knowledge_document ? true : false,
                'manage_channel_discussion' => $request->manage_channel_discussion ? true : false
            ]);

            return redirect()->route('jabatan.index')->with('success', 'Jabatan sudah ditambahkan');
        } catch (Exception $e) {
            dd($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $jabatan = Jabatan::find($id);

        return view('jabatan.edit', compact('jabatan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = Validator::make($request->all(), [
            'jabatan_name' => 'required'
        ]);

        if ($validate->fails()) {
            return redirect()->back()->with('error', $validate->errors()->first())->withInput();
        }

        try {
            $jabatan = Jabatan::findOrFail($id);
            $jabatan->update([
                'jabatan_name' => $request->jabatan_name,
                'access_knowledge_document' => $request->access_knowledge_document ? true : false,
                'upload_knowledge_document' => $request->upload_knowledge_document ? true : false,
                'download_knowledge_document' => $request->download_knowledge_document ? true : false,
                'verification_knowledge_document' => $request->verification_knowledge_document ? true : false,
                'create_channel_discussion' => $request->create_channel_discussion ? true : false,
                'verification_channel_discussion' => $request->verification_channel_discussion ? true : false,
                'manage_knowledge_document' => $request->manage_knowledge_document ? true : false,
                'manage_channel_discussion' => $request->manage_channel_discussion ? true : false
            ]);

            return redirect()->route('jabatan.index')->with('success', 'Jabatan sudah diupdate');
        } catch (Exception $e) {
            dd($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $jabatan = Jabatan::findOrFail($id);
        $jabatan->delete();
        return redirect()->route('jabatan.index')->with('success', 'Jabatan sudah dihapus');
    }
}

resources/views/jabatan/create.blade.php
@extends('layout.app')

@section('title', 'Create Jabatan - ' . env('APP_NAME'))

@section('headBody')
    @include('includes.breadcrumb', [
        'title' => 'Create Jabatan',
    ])
@endsection

@push('styles')
@endpush

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <form action="{{ route('jabatan.store') }}" method="POST">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label>Nama Jabatan</label>
                            <input type="text" class="form-control" name="jabatan_name" placeholder="Masukkan nama jabatan">
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="access_knowledge_document">
                                        <label class="form-check-label">Access Knowledge Document</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="upload_knowledge_document">
                                        <label class="form-check-label">Upload Knowledge Document</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="download_knowledge_document">
                                        <label class="form-check-label">Download Knowledge Document</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="verification_knowledge_document">
                                        <label class="form-check-label">Verification Knowledge Document</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="create_channel_discussion">
                                        <label class="form-check-label">Create Channel Discussion</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="verification_channel_discussion">
                                        <label class="form-check-label">Verification Channel Discussion</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="manage_knowledge_document">
                                        <label class="form-check-label">Manage Knowledge Document</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="manage_channel_discussion">
                                        <label class="form-check-label">Manage Channel Discussion</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{{ route('jabatan.index') }}" class="btn btn-warning">Batal</a>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
@endpush

resources/views/jabatan/edit.blade.php
@extends('layout.app')

@section('title', 'Edit Jabatan - ' . env('APP_NAME'))

@section('headBody')
    @include('includes.breadcrumb', [
        'title' => 'Edit Jabatan',
    ])
@endsection

@push('styles')
@endpush

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <form action="{{ route('jabatan.update', $jabatan->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                        <div class="form-group">
                            <label>Nama Jabatan</label>
                            <input type="text" class="form-control" name="jabatan_name" placeholder="Masukkan nama jabatan"
                                value="{{ $jabatan->jabatan_name }}">
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="access_knowledge_document"
                                            {{ $jabatan->access_knowledge_document ? 'checked' : '' }}>
                                        <label class="form-check-label">Access Knowledge Document</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="upload_knowledge_document"
                                            {{ $jabatan->upload_knowledge_document ? 'checked' : '' }}>
                                        <label class="form-check-label">Upload Knowledge Document</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="download_knowledge_document"
                                            {{ $jabatan->download_knowledge_document ? 'checked' : '' }}>
                                        <label class="form-check-label">Download Knowledge Document</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox"
                                            name="verification_knowledge_document"
                                            {{ $jabatan->verification_knowledge_document ? 'checked' : '' }}>
                                        <label class="form-check-label">Verification Knowledge Document</label>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="create_channel_discussion"
                                            {{ $jabatan->create_channel_discussion ? 'checked' : '' }}>
                                        <label class="form-check-label">Create Channel Discussion</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox"
                                            name="verification_channel_discussion"
                                            {{ $jabatan->verification_channel_discussion ? 'checked' : '' }}>
                                        <label class="form-check-label">Verification Channel Discussion</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="manage_knowledge_document"
                                            {{ $jabatan->manage_knowledge_document ? 'checked' : '' }}>
                                        <label class="form-check-label">Manage Knowledge Document</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" name="manage_channel_discussion"
                                            {{ $jabatan->manage_channel_discussion ? 'checked' : '' }}>
                                        <label class="form-check-label">Manage Channel Discussion</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{{ route('jabatan.index') }}" class="btn btn-warning">Batal</a>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
@endpush

resources/views/jabatan/index.blade.php
@extends('layout.app')

@section('title', 'Jabatan - ' . env('APP_NAME'))

@section('headBody')
    @include('includes.breadcrumb', [
        'title' => 'Jabatan',
    ])
@endsection

@push('styles')
@endpush

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="btn-group" style="margin-bottom: 1rem;">
                <a href="{{ route('jabatan.create') }}" class="btn btn-primary btn-sm" style="width: 8rem;">
                    <i class="fa fa-plus"></i> &nbsp; &nbsp;
                    Add Data
                </a>
            </div>
            <div class="card">
                <div class="card-header">
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-head-fixed text-nowrap table-striped table-hover datatable">
                        <thead>
                            <th>
                                #
                            </th>
                            <th>Nama Jabatan</th>
                            <th>Aksi</th>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(function() {
            var table = $('.datatable').DataTable({
                searching: false,
                destroy: true,
                processing: false,
                ordering: false,
                serverSide: true,
                ajax: {
                    url: "{{ route('jabatan.index') }}",
                    data: function(d) {
                        (d.jabatan = $('#jabatan').val())
                    },
                },
                columns: [{
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex'
                    },
                    {
                        data: 'jabatan_name',
                        name: 'jabatan_name'
                    },
                    {
                        data: 'action',
                        name: 'action'
                    }
                ],
            });

            @if (session('success'))
                Swal.fire({
                    icon: 'success',
                    title: 'Success...',
                    text: '{{ session('success') }}'
                });
            @endif

            @if (session('error'))
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: '{{ session('error') }}'
                });
            @endif
        });
    </script>
@endpush