routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'AuthController@login')->name('login');
Route::post('authenticating', 'AuthController@authenticating')->name('authenticating');

Route::group(['middleware' => ['auth']], function() {
    Route::post('logout', 'AuthController@logout')->name('logout');
    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::resource('user', 'UserController');
    Route::resource('jabatan', 'JabatanController');
    Route::resource('kategori', 'KategoriController');
    Route::resource('dokumen', 'DokumenController');
    Route::get('dokumen/verify/{id}', 'DokumenController@verify')->name('dokumen.verify');
    Route::get('diskusi', 'DiskusiController@index')->name('diskusi.index');
    Route::post('diskusi/getMessage', 'DiskusiController@getMessage')->name('diskusi.getMessage');
    Route::post('diskusi/sentMessage', 'DiskusiController@sentMessage')->name('diskusi.sentMessage');
    Route::post('diskusi/createChannel', 'DiskusiController@createChannel')->name('diskusi.createChannel');
    Route::post('diskusi/addpartisipant', 'DiskusiController@addUser')->name('diskusi.addPartisipant');
    Route::post('diskusi/createTag', 'DiskusiController@createTag')->name('diskusi.createtag');
});

app/Models/Dokumen.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dokumen extends Model
{
    protected $table = 'dokumen';
    protected $fillable = [
        'kategori_fk',
        'nama_dokumen',
        'url_dokumen',
        'user_fk',
        'is_verified'
    ];
}

app/Http/Controllers/DokumenController.php
<?php

namespace App\Http\Controllers;

use App\Models\Dokumen;
use App\Models\Jabatan;
use App\Models\Kategori;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\DataTables;

class DokumenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $jabatan_fk = Auth::user()->jabatan_fk;
        $jabatan = Jabatan::find($jabatan_fk);
        $kategori = Kategori::all();
        if ($request->ajax()) {
            $jabatanName = strtolower($jabatan->jabatan_name);
            $data = Dokumen::join('kategori', 'dokumen.kategori_fk', '=', 'kategori.id')
                ->join('users', 'dokumen.user_fk', '=', 'users.id')
                ->join('jabatan', 'users.jabatan_fk', '=', 'jabatan.id')
                ->where('kategori_fk', 'like', '%' . $request->input('kategori') . '%');

            if ($jabatanName != 'karyawan' && $jabatanName != 'supervisor') {
                $data->where('is_verified', 'like', '%' . $request->input('status') . '%%');
            } else {
                $data->where('is_verified', 1);
            }

            if ($request->input('stDate') != null  && $request->input('endDate')) {
                $stDate = Carbon::parse($request->input('stDate'))->startOfDay();
                $endDate = Carbon::parse($request->input('endDate'))->endOfDay();

                $data->whereBetween('created_at', [$stDate, $endDate]);
            }

            $data = $data->select(
                'dokumen.id as docs_id',
                'dokumen.nama_dokumen',
                'dokumen.url_dokumen',
                'dokumen.is_verified',
                'dokumen.created_at as dokumen_created_at',
                'kategori.category_name',
                'users.name as created_by',
                'jabatan.*'
            )->get();

            return DataTables::of($data)
                ->addIndexColumn()
                ->editColumn('is_verified', function ($row) {
                    if ($row->is_verified) {
                        $btn = '<span class="badge badge-success">Sudah diverifikasi</span>';
                    } else {
                        if ($row->verification_knowledge_document) {
                            $btn = '<a href="' . route('dokumen.verify', $row->docs_id) . '" class="btn btn-danger btn-sm" data-toggle="tooltip" title="Verifikasi Dokumen">
                                    Verifikasi
                                </a>';
                        } else {
                            $btn = '<span class="badge badge-warning">Akses dibatasi!</span>';
                        }
                    }

                    return $btn;
                })
                ->addColumn('download', function ($row) {
                    if ($row->download_knowledge_document && $row->is_verified) {
                        $btn = '
                        <a href="' . $row->url_dokumen . '" class="btn btn-success btn-circle btn-sm" data-toggle="tooltip" title="Download Dokumen">
                            <i class="fas fa-download"></i>
                        </a>
                        ';
                    } else {
                        $btn = '<span class="badge badge-warning">Akses dibatasi!</span>';
                    }
                    return $btn;
                })
                ->addColumn('action', function ($row) {
                    if ($row->is_verified) {
                        $btn = '
                        <form action="' . route('dokumen.destroy', $row->docs_id) . '" method="POST" id="delete-form">
                        ' . csrf_field() . '
                        ' . method_field('DELETE') . '
                            <button type="button" class="btn btn-primary btn-circle btn-sm btnShow" data-id="' . $row->docs_id . '" data-toggle="tooltip" title="Lihat Dokumen">
                                <i class="fas fa-eye"></i>
                            </button>
                        ';

                            if ($row->manage_knowledge_document) {
                                $btn .= '
                            <button type="button" class="btn btn-danger btn-circle btn-sm btnSubmit" data-toggle="tooltip" title="Hapus Dokumen">
                                <i class="fas fa-trash"></i>
                            </button>
                            ';
                            }

                            $btn .= '</form>';
                    } else {
                        $btn = '<span class="badge badge-warning">Akses dibatasi!</span>';
                    }
                    return $btn;
                })
                ->rawColumns(['is_verified', 'download', 'action'])
                ->make(true);
        }

        return view('dokumen.index', compact('jabatan', 'kategori'));
    }

    public function verify($id)
    {
        $dokumen = Dokumen::findOrFail($id);
        $dokumen->update(['is_verified' => 1]);

        return redirect()->route('dokumen.index')->with('success', 'Dokumen berhasil di verifikasi.');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $kategori = Kategori::all();
        return view('dokumen.create', compact('kategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = Validator::make($request->all(), [
            'nama_dokumen' => 'required',
            'kategori' => 'required',
            'file' => 'required|file'
        ]);

        if ($validate->fails()) {
            return redirect()->back()->with('error', $validate->errors()->first())->withInput();
        }

        $file = $request->file('file');
        $namafile = str_replace(' ', '_', strtolower($request->nama_dokumen));
        $path = $namafile . '.' . $file->getClientOriginalExtension();
        $file->move(public_path('uploads/document'), $path);

        Dokumen::create([
            'kategori_fk' => $request->kategori,
            'nama_dokumen' => $request->nama_dokumen,
            'url_dokumen' => url('uploads/document/' . $path),
            'user_fk' => Auth::user()->id,
            'is_verified' => false
        ]);

        return redirect()->route('dokumen.index')->with('success', 'Dokumen berhasil ditambahkan.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dokumen = Dokumen::find($id);
        $previewUrl = 'https://docs.google.com/viewer?url=' . urlencode($dokumen->url_dokumen) . '&embedded=true';

        return response()->json(['url' => $previewUrl]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dokumen = Dokumen::findOrFail($id);
        $dokumen->delete();

        return redirect()->route('dokumen.index')->with('success', 'Data berhasil dihapus');
    }

    public function documentVerify($id)
    {
        $dokumen = Dokumen::findOrFail($id);
        $dokumen->update(['is_verified' => 1]);

        return redirect()->route('dokumen.index')->with('success', 'Dokumen berhasil di verifikasi.');
    }
}

resources/views/dokumen/create.blade.php
@extends('layout.app')

@section('title', 'Create Dokumen - ' . env('APP_NAME'))

@section('headBody')
    @include('includes.breadcrumb', [
        'title' => 'Create Dokumen'
    ])
@endsection

@push('styles')

@endpush

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <form action="{{ route('dokumen.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label>Nama Dokumen</label>
                            <input type="text" class="form-control" name="nama_dokumen" placeholder="Masukkan nama dokumen">
                        </div>
                        <div class="form-group">
                            <label>Kategori</label>
                            <select class="form-control" name="kategori">
                                <option value="">--Pilih Kategori--</option>
                                @foreach ($kategori as $k)
                                <option value="{{ $k->id }}">{{ $k->category_name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>File</label>
                            <input type="file" class="form-control" name="file">
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{{ route('dokumen.index') }}" class="btn btn-warning">Batal</a>
                        &nbsp;
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('scripts')

@endpush

resources/views/dokumen/index.blade.php
@extends('layout.app')

@section('title', 'Dokumen - ' . env('APP_NAME'))

@section('headBody')
    @include('includes.breadcrumb', [
        'title' => 'Dokumen',
    ])
@endsection

@push('styles')
@endpush

@section('content')
    <div class="row">
        <div class="col-lg-12">
            @if ($jabatan->upload_knowledge_document)
                <div class="btn-group" style="margin-bottom: 1rem;">
                    <a href="{{ route('dokumen.create') }}" class="btn btn-primary btn-sm" style="width: 8rem;">
                        <i class="fa fa-plus"></i> &nbsp; &nbsp;
                        Add Data
                    </a>
                </div>
            @endif
            <div class="card">
                <div class="card-header">
                    <div class="card-tools">
                        <div class="input-group input-group-sm">
                            @if (strtolower($jabatan->jabatan_name) != 'supervisor' && strtolower($jabatan->jabatan_name) != 'karyawan')
                                <select class="form-control float-right" name="status" id="status">
                                    <option value="">-- pilih status --</option>
                                    <option value="0">Belum Verifikasi</option>
                                    <option value="1">Sudah Verifikasi</option>
                                </select>
                                &nbsp; &nbsp;
                            @endif
                            Start Date &nbsp;
                            <input type="date" class="form-control float-right" name="stDate" id="stDate"
                                placeholder="Start Date" value="">
                            &nbsp; &nbsp;
                            End Date &nbsp;
                            <input type="date" class="form-control float-right" name="endDate" id="endDate"
                                placeholder="End Date" value="">
                            &nbsp; &nbsp;
                            <select class="form-control float-right" name="kategori" id="kategori">
                                <option value="">-- pilih kategori --</option>
                                @foreach ($kategori as $k)
                                    <option value="{{ $k->id }}">{{ $k->category_name }}</option>
                                @endforeach
                            </select>
                            &nbsp; &nbsp;
                            <button class="btn btn-secondary btn btn-sm" id="btnSearch">
                                Cari
                            </button>
                        </div>
                    </div>
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-head-fixed text-nowrap table-striped table-hover datatable">
                        <thead>
                            <th>#</th>
                            <th>Nama Dokumen</th>
                            <th>Kategori</th>
                            <th>Dibuat</th>
                            <th>Is verified</th>
                            <th>Download</th>
                            <th>Aksi</th>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(function() {
            var table = $('.datatable').DataTable({
                searching: false,
                destroy: true,
                processing: false,
                ordering: false,
                serverSide: true,
                ajax: {
                    url: "{{ route('dokumen.index') }}",
                    data: function(d) {
                        (d.stDate = $('#stDate').val()),
                        (d.endDate = $('#endDate').val()),
                        (d.kategori = $('#kategori').val()),
                        (d.status = $('#status').val())
                    }
                },
                columns: [{
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex'
                    },
                    {
                        data: 'nama_dokumen',
                        name: 'nama_dokumen'
                    },
                    {
                        data: 'category_name',
                        name: 'category_name'
                    },
                    {
                        data: 'created_by',
                        name: 'created_by'
                    },
                    {
                        data: 'is_verified',
                        name: 'is_verified'
                    },
                    {
                        data: 'download',
                        name: 'download'
                    },
                    {
                        data: 'action',
                        name: 'action'
                    }
                ],
            });

            $('#btnSearch').unbind('click').click(function() {
                table.draw();
            });

            $(document).on('click', '.btnShow', function(e) {
                e.preventDefault();
                var id = $(this).data('id');
                $.ajax({
                    url: "{{ route('dokumen.show', ':id') }}".replace(':id', id),
                    type: 'GET',
                    success: function(res) {
                        window.open(res.url, '_blank');
                    }
                });
            });

            $(document).on('click', '.btnSubmit', function(e) {
                e.preventDefault();
                Swal.fire({
                    title: 'Apakah anda yakin?',
                    text: "Data yang dihapus tidak dapat dikembalikan!",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: '<i class="fa fa-trash"></i> Ya, hapus!',
                }).then((result) => {
                    if (result.isConfirmed) {
                        var form = $(this).closest('form');
                        form.submit();
                    }
                });
            });

            @if (session('success'))
                Swal.fire({
                    icon: 'success',
                    title: 'Success...',
                    text: '{{ session('success') }}'
                });
            @endif

            @if (session('error'))
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: '{{ session('error') }}'
                });
            @endif
        });
    </script>
@endpush