routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', 'AuthController@login')->name('login');
Route::post('authenticating', 'AuthController@authenticating')->name('authenticating');

Route::group(['middleware' => ['auth']], function() {
    Route::post('logout', 'AuthController@logout')->name('logout');
    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::resource('user', 'UserController');
    Route::resource('jabatan', 'JabatanController');
    Route::resource('kategori', 'KategoriController');
    Route::resource('dokumen', 'DokumenController');
    Route::get('dokumen/verify/{id}', 'DokumenController@verify')->name('dokumen.verify');
    Route::get('diskusi', 'DiskusiController@index')->name('diskusi.index');
    Route::post('diskusi/getMessage', 'DiskusiController@getMessage')->name('diskusi.getMessage');
    Route::post('diskusi/sentMessage', 'DiskusiController@sentMessage')->name('diskusi.sentMessage');
    Route::post('diskusi/createChannel', 'DiskusiController@createChannel')->name('diskusi.createChannel');
    Route::post('diskusi/addpartisipant', 'DiskusiController@addUser')->name('diskusi.addPartisipant');
    Route::post('diskusi/createTag', 'DiskusiController@createTag')->name('diskusi.createtag');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'password',
        'jabatan_fk'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Jabatan;
use App\Models\User;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Yajra\DataTables\DataTables;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = User::join('jabatan', 'users.jabatan_fk', '=', 'jabatan.id')
            ->where('users.jabatan_fk', 'like', '%' . $request->jabatan . '%')
            ->select(
                'users.*',
                'jabatan.jabatan_name'
            )
            ->orderBy('users.created_at', 'DESC')
            ->get();
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $btn = '
                    <form action="' . route('user.destroy', $row->id) . '" method="POST" id="delete-form">
                    ' . csrf_field() . '
                    ' . method_field('DELETE') . '
                        <a href="' . route('user.edit', $row->id) . '" data-toggle="tooltip" title="Edit Jabatan" class="btn btn-warning btn-circle btn-sm edit"><i class="fas fa-edit"></i></a>
                        <button type="submit" id="btn-submit" class="btn btn-danger btn-circle btn-sm" data-toggle="tooltip" title="Hapus Jabatan">
                            <i class="fas fa-trash"></i>
                        </button>
                    </form>
                    ';
                    return $btn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        $jabatan = Jabatan::all();
        return view('user.index', compact('jabatan'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $jabatan = Jabatan::all();
        return view('user.create', compact('jabatan'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = Validator::make($request->all(), [
            'name' => 'required|max:100',
            'username' => 'required|max:100|unique:users,username',
            'email' => 'required|email|max:200',
            'password' => 'required|min:8',
            'jabatan' => 'required'
        ]);

        if ($validate->fails()) {
            return redirect()->back()->with('error', $validate->errors()->first())->withInput();
        }

        try {
            User::create([
                'name' => $request->name,
                'username' => $request->username,
                'email' => $request->email,
                'password' => Hash::make($request->password),
                'jabatan_fk' => $request->jabatan
            ]);

            return redirect()->route('user.index')->with('success', 'Berhasil membuat user.');
        } catch (Exception $e) {
            return redirect()->back()->with('error', $e->getMessage())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        $jabatan = Jabatan::all();

        return view('user.edit', compact('user', 'jabatan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validate = Validator::make($request->all(), [
            'name' => 'required|max:100',
            'username' => 'required|max:100',
            'email' => 'required|email|max:200',
            // 'password' => 'required|min:8',
            'jabatan' => 'required'
        ]);

        if ($validate->fails()) {
            return redirect()->back()->with('error', $validate->errors()->first())->withInput();
        }

        $user = User::findOrFail($id);
        $user->name = $request->name;
        $user->username =  $request->username;
        $user->email = $request->email;
        if (isset($request->password)) {
            $user->password = $request->password;
        }
        $user->jabatan_fk = $request->jabatan;

        $user->save();

        return redirect()->route('user.index')->with('success', 'Success update data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('user.index')->with('success', 'Success delete data');
    }
}

resources/views/user/create.blade.php
@extends('layout.app')

@section('title', 'Create User - ' . env('APP_NAME'))

@section('headBody')
    @include('includes.breadcrumb', [
        'title' => 'Create User',
    ])
@endsection

@push('styles')
@endpush

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <form action="{{ route('user.store') }}" method="POST">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label>Nama</label>
                            <input type="text" class="form-control" name="name" placeholder="Masukkan nama">
                        </div>
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" class="form-control" name="username" placeholder="Masukkan username">
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="email" class="form-control" name="email" placeholder="Masukkan email">
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" class="form-control" name="password" placeholder="Masukkan password">
                        </div>
                        <div class="form-group">
                            <label>Jabatan</label>
                            <select class="form-control" name="jabatan">
                                <option value="">--Select Employee--</option>
                                @foreach ($jabatan as $j)
                                    <option value="{{ $j->id }}">{{ $j->jabatan_name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{{ route('user.index') }}" class="btn btn-warning">Batal</a>
                        &nbsp;
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
<script>
    $(function() {
        @if (session('success'))
                Swal.fire({
                    icon: 'success',
                    title: 'Success...',
                    text: '{{ session('success') }}'
                });
            @endif

            @if (session('error'))
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: '{{ session('error') }}'
                });
            @endif
    });
</script>
@endpush

resources/views/user/edit.blade.php
@extends('layout.app')

@section('title', 'Edit User - ' . env('APP_NAME'))

@section('headBody')
    @include('includes.breadcrumb', [
        'title' => 'Edit User',
    ])
@endsection

@push('styles')
@endpush

@section('content')
    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <form action="{{ route('user.update', $user->id) }}" method="POST">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                        <div class="form-group">
                            <label>Nama</label>
                            <input type="text" class="form-control" name="name" placeholder="Masukkan nama" value="{{ $user->name }}">
                        </div>
                        <div class="form-group">
                            <label>Username</label>
                            <input type="text" class="form-control" name="username" placeholder="Masukkan username" value="{{ $user->username }}">
                        </div>
                        <div class="form-group">
                            <label>Email</label>
                            <input type="email" class="form-control" name="email" placeholder="Masukkan email" value="{{ $user->email }}">
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="password" class="form-control" name="password" placeholder="Masukkan password">
                            <small class="text-danger">jangan diisi jika tidak mengubah password</small>
                        </div>
                        <div class="form-group">
                            <label>Jabatan</label>
                            <select class="form-control" name="jabatan">
                                <option value="">--Select Employee--</option>
                                @foreach ($jabatan as $j)
                                    <option value="{{ $j->id }}" {{ $user->jabatan_fk == $j->id ? 'selected' : '' }}>{{ $j->jabatan_name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="card-footer">
                        <a href="{{ route('user.index') }}" class="btn btn-warning">Batal</a>
                        &nbsp;
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
<script>
    $(function() {
        @if (session('success'))
                Swal.fire({
                    icon: 'success',
                    title: 'Success...',
                    text: '{{ session('success') }}'
                });
            @endif

            @if (session('error'))
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: '{{ session('error') }}'
                });
            @endif
    });
</script>
@endpush

resources/views/user/index.blade.php
@extends('layout.app')

@section('title', 'User - ' . env('APP_NAME'))

@section('headBody')
    @include('includes.breadcrumb', [
        'title' => 'User',
    ])
@endsection

@push('styles')
@endpush

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="btn-group" style="margin-bottom: 1rem;">
                <a href="{{ route('user.create') }}" class="btn btn-primary btn-sm" style="width: 8rem;">
                    <i class="fa fa-plus"></i> &nbsp; &nbsp;
                    Add Data
                </a>
            </div>
            <div class="card">
                <div class="card-header">
                    <div class="card-tools">
                        <div class="input-group input-group-sm">
                            <select class="form-control float-right" name="jabatan" id="jabatan">
                                <option value="">--Select Employee--</option>
                                @foreach ($jabatan as $j)
                                    <option value="{{ $j->id }}">{{ $j->jabatan_name }}</option>
                                @endforeach
                            </select>
                            &nbsp; &nbsp; &nbsp;
                            <button type="button" class="btn btn-secondary btn-sm" id="btnReset">
                                Reset
                            </button>
                            &nbsp; &nbsp; &nbsp;
                            <button type="button" class="btn btn-secondary btn-sm" id="btnSearch">
                                Cari
                            </button>
                        </div>
                    </div>
                </div>
                <div class="card-body table-responsive">
                    <table class="table table-head-fixed text-nowrap table-striped table-hover datatable">
                        <thead>
                            <th>
                                #
                            </th>
                            <th>Name</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Jabatan</th>
                            <th>Aksi</th>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $(function() {
            var table = $('.datatable').DataTable({
                searching: false,
                destroy: true,
                processing: false,
                ordering: false,
                serverSide: true,
                ajax: {
                    url: "{{ route('user.index') }}",
                    data: function(d) {
                        (d.jabatan = $('#jabatan').val())
                    },
                },
                columns: [{
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex'
                    },
                    {
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'username',
                        name: 'username'
                    },
                    {
                        data: 'email',
                        name: 'email'
                    },
                    {
                        data: 'jabatan_name',
                        name: 'jabatan_name'
                    },
                    {
                        data: 'action',
                        name: 'action'
                    }
                ],
            });

            @if (session('success'))
                Swal.fire({
                    icon: 'success',
                    title: 'Success...',
                    text: '{{ session('success') }}'
                });
            @endif

            @if (session('error'))
                Swal.fire({
                    icon: 'error',
                    title: 'Oops...',
                    text: '{{ session('error') }}'
                });
            @endif
        });
    </script>
@endpush